### PR TITLE
Fix MeshLoadDoneFunc type to include err

### LINKED ISSUE #230: TypeScript types incorrectly exclude the `err` argument from `MeshLoadDoneFunc`
I have an extension class in my application that does a few things, one of them being coercing `URDFLoader` into the same shape as `Loader<T>` from Three so that `react-three-fiber` is happy to call it from its `useLoader` hook. I also overrode `loadMeshCb` to allow me to call a custom function on each mesh on a per-robot basis.

While making that `loadMeshCb` override, I discovered that the `onLoad` argument of form `(obj: Object3D, err: any) => void` is typed in the `.d.ts` file as 
```
interface MeshLoadDoneFunc {
    (mesh: Object3D): void
}
```

And thus had to ignore compiler errors via `@ts-ignore` or `@ts-expect-error` to properly override the function.

### PR DESCRIPTION
**Pull request by EzraBrooks**
Fixes #230.

### CODE REVIEW

File: javascript/src/URDFLoader.d.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { LoadingManager, Object3D } from 'three';
 import { URDFRobot } from './URDFClasses';
 
 interface MeshLoadDoneFunc {
-    (mesh: Object3D): void;
+    (mesh: Object3D, err: any): void;
```
Comment (gkjohnson) [inline javascript/src/URDFLoader.d.ts:5]: Can we make "err" optional and report that it should be of type Error?

```
(mesh: Object3D, err?: Error)
```

Additionally it looks like the docs could be updated to include the error argument, as well:

https://github.com/gkjohnson/urdf-loaders/blob/master/javascript/README.md?plain=1#L147

**Review by gkjohnson — CHANGES_REQUESTED** [review]

File: javascript/src/URDFLoader.d.ts (hunk 1 above)
Comment (EzraBrooks) [reply javascript/src/URDFLoader.d.ts:5]: Sure. Given that I hadn't seen the `err` argument in use, I wasn't sure what type it would be. I'll make that change and update the docs.

**Comment by gkjohnson** [comment]
This is great, thank you! I'll publish a new release now.
